@startuml


object "Extract" as extract
AbstractIOService --|> extract

object "Transform" as transform
AbstractRenderService --|> transform

object "Load" as load
AbstractIOService --|> load


object "Abstract\nIO Service" as AbstractIOService
object "File\nIO Service" as FileIOService
object "Envirnoment\nIO Service" as EnvirnomentIOService
object "HTTP\nIO Service" as HTTPIOService
object "AWS S3\nIO Service" as AWSS3IOService

FileIOService --|> AbstractIOService
EnvirnomentIOService --|> AbstractIOService
HTTPIOService --|> AbstractIOService
AWSS3IOService --|> AbstractIOService



object "Abstract\nRender Service" as AbstractRenderService
object "Handlebars\nRender Service" as HandlebarsRenderService
object "EJS\nRenderService" as EJSRenderService

EJSRenderService --|> AbstractRenderService
HandlebarsRenderService --|> AbstractRenderService

object "Yaml Util" as yamlUtil


@enduml