	
@startuml
actor User as user
boundary "Yaml-Render" as yamlrender
boundary "Yaml-Util" as util
boundary "Render" as render
boundary "I/O" as io
user -> yamlrender : Provide configuration reference
yamlrender -> io : Get Configuration
io -> yamlrender : Return Configuration
yamlrender -> util : Build Configuration
loop for each - depth first
	util -> io : Get External Reference Configuration
	io -> util : Return External Reference Configuration
end
util -> util : Build Internal Configuration
util -> yamlrender : Return Configuration Build
loop for each
	yamlrender -> render : Get Render
	render -> yamlrender : Return Render
	yamlrender -> io : Save Render
	io -> yamlrender : Return Save Confirmation
end
group Optional
	yamlrender -> io : Save Result Log
	io -> yamlrender : Return Save Confirmation
	yamlrender -> yamlrender : Add reference to Result Log
end
group Optional Human Readable Log
	yamlrender -> render : Render Human Readable Result Log
	render ->  yamlrender : Return Human Readable Result Log
	yamlrender -> io : Save Human Readable Result Log
	io -> yamlrender : Return Save Confirmation
	yamlrender -> yamlrender : Add reference to Result Log
end
yamlrender -> user : Return Result Log
@enduml