quadrantChart
    title Power vs Interest/Influence Matrix
    x-axis Low Power --> High Power
    y-axis Low Interest --> High Interest
    quadrant-1 "Manage Closely\nKey Players"
    quadrant-2 Keep Satisfied
    quadrant-3 Monitor with Mimimum Effoirt
    quadrant-4 Keep Informed
    Stakeholder A: [0.3, 0.6]
    Stakeholder B: [0.45, 0.23]
    Stakeholder C: [0.57, 0.69]
    Stakeholder D: [0.78, 0.34]
    Stakeholder E: [0.40, 0.34]
    Stakeholder F: [0.35, 0.78]