---
context:
  $YamlFile: ./output/context.yml

views:
  index: ./views/index.ejs
  error: ./views/error.ejs
  about:
    index: ./views/index.ejs
    team: ./views/teams.ejs
  publications:
    index: ./views/publication/index.ejs
    details: ./views/publication/details.ejs
  service:
    index: ./views/services/index.ejs
    details: ./views/services/details.ejs
  portfolio:
    index: ./views/portfolio/index.ejs
    details: ./views/portfolio/details.ejs

render:
  - id: home
    template:
      type: EJS
      path:
        $Ref: views.index
    context:
      $Ref: context
    output:
      type: FILE
      path: ./output/index.html
  - id: about
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.about.index
    output:
      type: FILE
      path: ./output/about.html
  - id: service
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.index
    output:
      type: FILE
      path: ./output/service.html
  - id: projectmanagement
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/projectmanagement.html
  - id: uxdesign
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: html
      path: ./output/service/uxdesign.html
  - id: analysisresearch
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/analysisresearch.html
  - id: facilitationcoaching
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/facilitationcoaching.html
  - id: publication
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FIlE
      path: ./output/publication.html
  - id: publication_article
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/publication/article.html
