---
context: &context
  $File: ../output/content.yml

breadcrumbs: &breadcrumbs
  root:
    href: /index.html
    title: Home

views:
  index: ./views/index.ejs
  error: ./views/error.ejs
  about:
    index: ./views/about/index.ejs
    team: ./views/teams.ejs
  publications:
    index: ./views/publication/index.ejs
    details: ./views/publication/details.ejs
  service:
    index: ./views/services/index.ejs
    details: ./views/services/details.ejs
  portfolio:
    index: ./views/portfolio/index.ejs
    details: ./views/portfolio/details.ejs

render:
  - id: home
    template:
      type: EJS
      path:
        $Ref: views.index
    context:
      page: home
    output:
      type: FILE
      path: ./output/index.html

# About
  - id: about
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: About Us
        items: []
    template:
      type: EJS
      path:
        $Ref: views.about.index
    output:
      type: FILE
      path: ./output/about.html
  - id: waywework
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Way We Work
        items:
          - href: /about.html
            title: About Us
      publication:
        $Ref: context.about.aboutContent.waywework
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/about/waywework.html
  - id: whoweare
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Who We Are
        items:
          - href: /about.html
            title: About Us
      publication:
        $Ref: context.about.aboutContent.whoweare
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/about/whoweare.html
  - id: ourmission
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Our Mission
        items:
          - href: /about.html
            title: About Us
      publication:
        $Ref: context.about.aboutContent.ourmission
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/about/ourmission.html
  - id: ourvalues
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Our Values
        items:
          - href: /about.html
            title: About Us
      publication:
        $Ref: context.about.aboutContent.ourvalues
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/about/ourvalues.html
  - id: ourvision
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Our Vision
        items:
          - href: /about.html
            title: About Us
      publication:
        $Ref: context.about.aboutContent.ourvision
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/about/ourvision.html




# Service
  - id: service
    context:
      page: services
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Services
        items: []     
    template:
      type: EJS
      path:
        $Ref: views.service.index
    output:
      type: FILE
      path: ./output/service.html
  - id: projectmanagement
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Project, Program & Portfolio Management
        items:
          - href: /service.html
            title: Services
      publication:
        $Ref: context.services.serviceContent.projectmanagement
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/service/projectmanagement.html
  - id: uxdesign
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: UX Design
        items:
          - href: /service.html
            title: Services
      publication:
        $Ref: context.services.serviceContent.uxdesign
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/service/uxdesign.html
  - id: analysisresearch
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Business Analysis & Research
        items:
          - href: /service.html
            title: Services
      publication:
        $Ref: context.services.serviceContent.analysisresearch
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/service/analysisresearch.html
  - id: facilitationcoaching
    context:
      page: about
      breadcrumbs:
        <<: *breadcrumbs
        current:
          title: Facilitation & Coaching
        items:
          - href: /service.html
            title: Services
      publication:
        $Ref: context.services.serviceContent.facilitationcoaching
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/service/facilitationcoaching.html
       
temp:
  - id: projectmanagement
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/projectmanagement.html
  - id: uxdesign
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: html
      path: ./output/service/uxdesign.html
  - id: analysisresearch
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/analysisresearch.html
  - id: facilitationcoaching
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FILE
      path: ./output/service/facilitationcoaching.html
  - id: publication
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.service.details
    output:
      type: FIlE
      path: ./output/publication.html
  - id: publication_article
    context:
      $Ref: context
    template:
      type: EJS
      path:
        $Ref: views.publications.details
    output:
      type: FILE
      path: ./output/publication/article.html
