@startmindmap
* Site
** As Is
*** Home
**** About
***** Who We Are
***** The Way We Work
***** Our Mission
***** Our Vision
***** Our Values
**** Services
***** Project, Program & Portfolio Management
***** Business Analysis & Research
***** UX Research, Analysis & Design
***** Facilitation & Couching
**** Publications
***** Articles
-- To Be
--- Option 1
---- Home
----- About
------ Who We Are
------ The Way We Work
------ Our Mission
------ Our Vision
------ Our Values
----- Services
------ Management
------- Project Management
------- Product Management
------- Portfolio Management
------- Program Management
------- Change Management
------ Analysis & Research
------- UX Analysis & Research
------- Business Analysis & Research
------- Marketing & Reserach
------- Value Stream Analysis
------ Development & Design
------- UX Design
------- Business Design
------- IT Development
------ Digitalization
----- Publications
------ Articles
------- Article
------ Videos
------- Videos
--- Option 2
---- Home
----- About
------ Who We Are
------ The Way We Work
------ Our Mission
------ Our Vision
------ Our Values
------ Our People
----- Services
----- Publications
------ Management
------- Project Management
------- Product Management
------- Portfolio Management
------- Program Management
------- Change Management
------ Analysis & Research
------- UX Analysis & Research
------- Business Analysis & Research
------- Marketing & Reserach
------- Value Stream Analysis
------ Development & Design
------- UX Design
------- Business Design
------- IT Development
------ Digitalization
@endmindmap